### PR TITLE
Small bug fixing

### LINKED ISSUE #1212: Storm Staff uncraftable, magic sugar is always consumed instead of placed as ingredient on altar
## Description (Required)
Attempt to craft elemental staff - storm, but magic sugar is always consumed instead of being placed onto the altar, so item can not be crafted (recipe is never complete).

## Steps to reproduce the Issue (Required)
*Speed V instantly applied to player instead of being placed on altar.

## Expected behavior (Required)
Need an exception for this item when it is being used on an altar block (similar to how empty flasks of knowledge work already).

## Server Log / Error Report
No log activity.

## Environment (Required)
[14:48:54 INFO]: Paper v1_14_R1 (223)
[14:48:54 INFO]:
[14:48:54 INFO]: CS-CoreLib vDEV - 78 (git 199e1b1e)
[14:48:54 INFO]: Slimefun vDEV - 327 (git 7ba0eba4)
[14:48:54 INFO]:
[14:48:54 INFO]: Installed Addons (13)
[14:48:54 INFO]:  Barrels vDEV - 7 (git 0d14dd9f)
[14:48:54 INFO]:  SlimeXpansion vDEV - 4 (git 5bf10c29)
[14:48:54 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[14:48:54 INFO]:  ChestTerminal vDEV - 17 (git 933a7d36)
[14:48:54 INFO]:  EmeraldEnchants vDEV - 5 (git 6adbbb87)
[14:48:54 INFO]:  HotbarPets vDEV - 20 (git cd87bc60)
[14:48:54 INFO]:  ExoticGarden vDEV - 22 (git a855f5b7)
[14:48:54 INFO]:  SoulJars vDEV - 4 (git 4a600aa2)
[14:48:54 INFO]:  SlimefunOreChunks vDEV - 2 (git 24d90a3e)
[14:48:54 INFO]:  ElectricSpawners vDEV - 5 (git c3f8cc9d)
[14:48:54 INFO]:  ExtraHeads v1.1
[14:48:54 INFO]:  PrivateStorage vDEV - 6 (git b012877e)
[14:48:54 INFO]:  DyedBackpacks vDEV - 1 (git 4b4d1f0f)

### LINKED ISSUE #1379: debug fish error in 1.15.2
## Description (Required)
Error happens when right clicking a sf block with the debug fish.

## Steps to reproduce the Issue (Required)
Right click slimefun block with a debug fish (my target for this was an input node)
https://pastebin.com/jjpCZK8R

## Expected behavior (Required)
Same behavior without the error.

## Server Log / Error Report
https://pastebin.com/jjpCZK8R

## Environment (Required)
[21:59:04 INFO]: Paper v1_15_R1 (67)
[21:59:04 INFO]:
[21:59:04 INFO]: CS-CoreLib vDEV - 80 (git e3242c60)
[21:59:04 INFO]: Slimefun vDEV - 408 (git 73b64e87)
[21:59:04 INFO]:
[21:59:04 INFO]: Installed Addons (12)
[21:59:04 INFO]:  DyedBackpacks vDEV - 1 (git 4b4d1f0f)
[21:59:04 INFO]:  ElectricSpawners vDEV - 6 (git 845b6076)
[21:59:04 INFO]:  SlimefunOreChunks vDEV - 3 (git 7ddf966e)
[21:59:04 INFO]:  SlimeXpansion vDEV - 4 (git 5bf10c29)
[21:59:04 INFO]:  ExtraHeads vDEV - 9 (git 32435a1f)
[21:59:04 INFO]:  SoulJars vDEV - 10 (git 58202ab6)
[21:59:04 INFO]:  HotbarPets vDEV - 23 (git 37b50104)
[21:59:04 INFO]:  SlimyTreeTaps vDEV - 3 (git c4f773fa)
[21:59:04 INFO]:  PrivateStorage vDEV - 8 (git 6b242fc5)
[21:59:04 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[21:59:04 INFO]:  ChestTerminal vDEV - 20 (git a698c614)
[21:59:04 INFO]:  ExoticGarden vDEV - 25 (git b5fce971)

### PR DESCRIPTION
**Pull request by BigBadE**
## Description

Fixed Magic Sugar not able to be placed on Ancient Altars, and fixed Debug Fish on heads placed on walls.

## Changes

Added an id check to MagicSugar.java and added a check if the head is a wall head and if so use Directional instead of Rotatable for DebugFishListener.java

## Related Issues

Resolves #1379 
Resolves #1212 

## Testability

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.

### CODE REVIEW

**Comment by BigBadE** [comment]
Missed a null check on block data

**Comment by WalshyDev** [comment]
With all the formatting changes it's hard to see what really changed in the debug fish code.

**Comment by BigBadE** [comment]
@WalshyDev Sorry about those, I don't know why Git deleted and readded every line when I just deleted a single new line. Changes are lines 59-61.

File: src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/MagicSugar.java [hunk 1]
```diff
@@ -23,6 +26,11 @@ public MagicSugar(Category category, SlimefunItemStack item, RecipeType recipeTy
 	public ItemInteractionHandler getItemHandler() {
 		return (e, p, item) -> {
 			if (isItem(item)) {
+				if(e.getClickedBlock() != null) {
+					String target = BlockStorage.checkID(e.getClickedBlock());
+					if ("ANCIENT_PEDESTAL".equals(target) || "ANCIENT_ALTAR".equals(target))
+						return false;
```
Comment (TheBusyBiscuit) [inline src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/MagicSugar.java]: This should return true.

True means "Yes this Item was me".
With false you are telling Slimefun to keep looking for items that match...

Comment (TheBusyBiscuit) [inline src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/MagicSugar.java]: I am also thinking whether a Material comparison for ENCHANTMENT_TABLE and DISPENSER may not be a better idea.
It would definitely be better performance-wise.
Also please add a comment to this code to explain why it is there.

Comment (BigBadE) [reply src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/MagicSugar.java]: I was thinking that too but added the check so that people don’t accidentally open inventories when trying to use the sugar. Tbh it would work either way.

**Comment by BigBadE** [comment]
Changed all things requested.
