### PR TITLE
Fixes #1098.

### LINKED ISSUE #1098: Rainbow Glass/Pane/Wool/Clay
## Description (Required)
Rainbow Glass - Rainbow Glass Pane - Rainbow Wool - Rainbow Clay.
Those items don't change the color and dissappear after a few seconds. 3 to 5 seconds.

## Steps to reproduce the Issue (Required)
The player who put the blocks is in survival mode. But you can reply this in Creative too.
https://imgur.com/sdv1u1k

## Expected behavior (Required)
When you put the blocks, they should change color (type of block).
## Server Log / Error Report
Rainbow Wool » https://pastebin.com/raw/fZdV4u0t
Rainbow Glass » https://pastebin.com/raw/4kEfxt8Z
Rainbow Glass Pane » https://pastebin.com/raw/pxGMLSGz
Rainbow Clay » https://pastebin.com/raw/xusvM0qp

## Environment (Required)
https://imgur.com/a/zF87cdh

### PR DESCRIPTION
**Pull request by LinoxGH**
## Description
Fixes ArrayIndexOutOfBounds exception in RainbowTicker#uniqueTick.

## Changes
Fixed the wrong index defining.

## Related Issues

#1098 

## Testability

- [X] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.

### CODE REVIEW

File: src/me/mrCookieSlime/Slimefun/Objects/tasks/RainbowTicker.java [hunk 1]
```diff
@@ -49,7 +49,7 @@ else if (MaterialHelper.isTerracotta(b.getType())){
 
 	@Override
 	public void uniqueTick() {
-		index = ((index == queue.length - 1) ? 0: index + 1);
+		index = ((index == queue[queue.length - 1]) ? 0: index + 1);
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/Objects/tasks/RainbowTicker.java]: Why are you comparing an index value with a data value here?
Please elaborate because I can see this causing a ton of problems.

Comment (ajan-12) [reply src/me/mrCookieSlime/Slimefun/Objects/tasks/RainbowTicker.java]: Tbh I don't know either how this is fixing the issue but I was doing trying stuff to see if it fixes the issue and magically this did.

Comment (TheBusyBiscuit) [reply src/me/mrCookieSlime/Slimefun/Objects/tasks/RainbowTicker.java]: It shouldn't though. So I am leaving it open for now.

Comment (ajan-12) [reply src/me/mrCookieSlime/Slimefun/Objects/tasks/RainbowTicker.java]: After a thought it worked because when I tested, I tested it for rainbow blocks which had these values in queue:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

When index needed to change its value was 15 which is also the last value in queue.
In the older version index became values like 767 for some reason which caused the ArrayIndexOutOfBounds exception in 53rd line.

Comment (ajan-12) [reply src/me/mrCookieSlime/Slimefun/Objects/tasks/RainbowTicker.java]: Just a theory, changing the == with >= in older code may also fix this.
Or adding a space before ":"

Comment (TheBusyBiscuit) [reply src/me/mrCookieSlime/Slimefun/Objects/tasks/RainbowTicker.java]: >= would have also been my suggestion to fix it.
But adding a space there won't do anything.

**Comment by LinoxGH** [comment]
Did the requested change but didn't test if this fixes the issue.

**Comment by TheBusyBiscuit** [comment]
Then I am gonna wait till you've tested it.

**Comment by LinoxGH** [comment]
Okay just tested and it works.
