### PR TITLE
Fixed Industrial Miner debris issue

### LINKED ISSUE #2203: Advanced industrial miner and industrial miner aren't working.
## Description (REQUIRED)
It uses the fuel but doesn't mine anything, in and outside of claims.

## Steps to reproduce the Issue (REQUIRED)
Make an industrial miner or an advanced industrial miner.
Place it.
Put fuel.
Use it.
and it won't mine anything.

## Expected behavior (REQUIRED)
For it to mine ores,

## Stacktrace
https://pastebin.com/sf3PM7Ly

## Environment (REQUIRED)
dfdgdfgdfgdfg

 - Server Software (Spigot/Paper): Tuinity 1.15.2
 - Minecraft Version: 1.15.2
 - Slimefun Version: vDEV - 623 (git d55a546c)
 - CS-CoreLib Version: vDEV - 83 (git 8081bb4f)

### PR DESCRIPTION
**Pull request by poma123**
## Description

Changed the canMine() method to check the name of the material. I think this is cleaner than using MinecraftVersion.isAtLeast() here. I also think that this change is enough, the upper getOutcome() method should be fine.

## Changes

- Changed canMine() in the class IndustrialMiner

## Related Issues

Fixes #2203 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
I think a MinecraftVersion#isAtLeast(1.16) check would be more appropriate here.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java [hunk 1]
```diff
@@ -212,7 +212,7 @@ public void onInteract(Player p, Block b) {
      * @return Whether this {@link IndustrialMiner} is capable of mining this {@link Material}
      */
     public boolean canMine(Material type) {
-        return type.name().endsWith("_ORE") || (type == Material.ANCIENT_DEBRIS && canMineAncientDebris.getValue());
+        return type.name().endsWith("_ORE") || (SlimefunPlugin.getMinecraftVersion().isAtLeast(MinecraftVersion.MINECRAFT_1_16) && type == Material.ANCIENT_DEBRIS && canMineAncientDebris.getValue());
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java:215]: Also, this is getting a bit too long for a single line I think.
It's probably better to restructure this:

if (ore) {
  return true;
}
else if (1.16) {
  return <debris stuff>
}
else {
  return false;
}

Comment (poma123) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java:215]: Got it
