### PR TITLE
Droid fix2

### LINKED ISSUE #997: Andriods cannot be broken.
## Description (Required)

Any type of andriods cannot be removed.

## Steps to reproduce the Issue (Required)

Place any type of Andriod (Normal, Advanced, Empowered) and try removing it.

## Expected behavior (Required)

The andriod being removed and its item being returned.

## Server Log / Error Report

No errors.

### PR DESCRIPTION
**Pull request by dniym**
Fixes #997

### CODE REVIEW

File: src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java [hunk 1]
```diff
@@ -1,1433 +1,1433 @@
...
+				if (!open) {
+					Messages.local.sendTranslation(p, "inventory.no-access", true);
+				}
+				return open;
+			}
+
+			@Override
+			public void newInstance(BlockMenu menu, final Block b) {
+				try {
+					menu.replaceExistingItem(15, new
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java]: This check might as well be removed. It shouldn't even be here, must have slipped through my code review in an earlier PR.
You can remove this line I think.

Comment (dniym) [reply src/me/mrCookieSlime/Slimefun/Android/ProgrammableAndroid.java]: Yeah I was debating removing it because i didn’t think the code would ever even get that far if it wasn’t in block storage.
