### PR TITLE
Fixes #2265 <Tested>

### LINKED ISSUE #2265: Fluid Pump: Lava dupe!
## Description (REQUIRED)

Buckets get filled from non-source water/lava. 

https://github.com/TheBusyBiscuit/Slimefun4/pull/2256

## Steps to reproduce the Issue (REQUIRED)

https://www.youtube.com/watch?v=quJMXYGEzb0

## Expected behavior (REQUIRED)

Shouldn't fillup buckets from non-source lava/water.

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.2-R0.1-SNAPSHOT
 - Slimefun Version: DEV - 648
 - CS-CoreLib Version: DEV - 79

### PR DESCRIPTION
**Pull request by LinoxGH**
## Description

Fixed all problems regarding Fluid Pump. But this time I also tested it.

## Changes

Made the check for source block before consuming energy and creating bucket.

## Related Issues

Fixes #2265 

## Checklist

- [X] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [X] I did my best to add documentation to any public classes or methods I added.
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java [hunk 1]
```diff
@@ -127,31 +127,39 @@ protected void tick(Block b) {
                     if (!menu.fits(bucket.get(), getOutputSlots())) {
                         return;
                     }
-
+                    
+                    Block consume = findFluid(fluid);
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:131]: Please give this variable a more meaningful name. `nextBlock` maybe?

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java [hunk 2]
```diff
@@ -127,31 +127,39 @@ protected void tick(Block b) {
...
-            if (fluid.getType() == Material.WATER || fluid.getType() == Material.BUBBLE_COLUMN) {
-                // With water we can be sure to find an infinite source whenever we go
-                // further than 2 blocks, so we can just remove the water here and save
-                // outselves all of that computing...
-                fluid.setType(Material.AIR);
-            }
-            else {
-                List<Block> list = Vein.find(fluid, RANGE, block -> isLiquid(block) && block.getType() == fluid.getType());
-                list.get(list.size() - 1).setType(Material.AIR);
+    private Block findFluid(Block fluid) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:144]: `findNextFluid` might be better here

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java [hunk 3]
```diff
@@ -127,31 +127,39 @@ protected void tick(Block b) {
...
+        if (fluid.getType() == Material.WATER || fluid.getType() == Material.BUBBLE_COLUMN) {
+            // With water we can be sure to find an infinite source whenever we go
+            // further than 2 blocks, so we can just remove the water here and save
+            // ourselves all of that computing...
+            return fluid;
+        }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:150]: We should probably also do an `isSource` check for fluid here now that I think about it...
Otherwise people will have infinite water sources, even if the water source isn't infinite.
Simply checking whether the block below (fluid) is a source block should be fine though.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java [hunk 4]
```diff
@@ -127,31 +127,39 @@ protected void tick(Block b) {
...
+        
+        if (fluid.getType() == Material.LAVA) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:152]: * `else if`

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java [hunk 5]
```diff
@@ -166,21 +174,21 @@ else if (fluid.getType() == Material.WATER || fluid.getType() == Material.BUBBLE
         }
     }
 
-    private boolean isLiquid(Block block) {
-        if (block.isLiquid()) {
+    private boolean isSource(Block block) {
+        if (isLiquid(block.getType())) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:178]: Why not Block#isLiquid() ?

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java (hunk 5 above)
Comment (LinoxGH) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:178]: That only returns true to lava and water. But we also want true for bubble columns.

Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:179]: Block#isLiquid() returns true for WATER, LAVA and BUBBLE_COLUMN.
It does the exact same like your method, only that it is a wrapper for NMS code which checks a flag. But that flag is set to true for all three.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java [hunk 6]
```diff
@@ -127,31 +127,40 @@ protected void tick(Block b) {
...
+            // further than 2 blocks, so we can just remove the water here and save
+            // ourselves all of that computing...
+            if (isSource(fluid)) {
+                return fluid;
             }
-            else {
-                List<Block> list = Vein.find(fluid, RANGE, block -> isLiquid(block) && block.getType() == fluid.getType());
-                list.get(list.size() - 1).setType(Material.AIR);
+            
+        } else if (fluid.getType() == Material.LAVA) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:153]: Please follow the existing formatting, the `else if` should go on the next line.

Comment (LinoxGH) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:153]: Ugh none of the changes I contributed to the plugin had else's in next lines lol

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java (hunk 5 above)
Comment (LinoxGH) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:180]: Well then spigot javadocs aren't complete...

Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/FluidPump.java:180]: To be honest... Does that really surprise you? :LUL:

**Review by TheBusyBiscuit — APPROVED** [review]
