### PR TITLE
fixed broken items

### LINKED ISSUE #1187: Explosive pickaxe/shovel not exploding
## Description (Required)
Just vanilla functionality with these two tools, currently.

## Steps to reproduce the Issue (Required)
Use either the explosive shovel or explosive pick on material

## Expected behavior (Required)
for 3x3 area of blocks to be destroyed as usual.

## Server Log / Error Report
No log activity.

## Environment (Required)
[18:06:16 INFO]: Paper v1_14_R1 (214)
[18:06:16 INFO]:
[18:06:16 INFO]: CS-CoreLib vDEV - 77 (git 6e171836)
[18:06:16 INFO]: Slimefun vDEV - 309 (git 20e3f2b9)
[18:06:16 INFO]:
[18:06:16 INFO]: Installed Addons (13)
[18:06:16 INFO]:  Barrels vDEV - 7 (git 0d14dd9f)
[18:06:16 INFO]:  SlimeXpansion vDEV - 4 (git 5bf10c29)
[18:06:16 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[18:06:16 INFO]:  ChestTerminal vDEV - 17 (git 933a7d36)
[18:06:16 INFO]:  EmeraldEnchants vDEV - 5 (git 6adbbb87)
[18:06:16 INFO]:  HotbarPets vDEV - 20 (git cd87bc60)
[18:06:16 INFO]:  ExoticGarden vDEV - 22 (git a855f5b7)
[18:06:16 INFO]:  SoulJars vDEV - 4 (git 4a600aa2)
[18:06:16 INFO]:  SlimefunOreChunks vDEV - 2 (git 24d90a3e)
[18:06:16 INFO]:  ElectricSpawners vDEV - 5 (git c3f8cc9d)
[18:06:16 INFO]:  ExtraHeads v1.1
[18:06:16 INFO]:  PrivateStorage vDEV - 6 (git b012877e)
[18:06:16 INFO]:  DyedBackpacks vDEV - 1 (git 4b4d1f0f)

### PR DESCRIPTION
**Pull request by J3fftw1**
## Description

fixed broken items
## Changes

fixed broken items
## Related Issues

Fixes #1187 
## Testability

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.

### CODE REVIEW

File: src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/PickaxeOfContainment.java [hunk 1]
```diff
@@ -23,7 +23,17 @@
...
-	
+
+	@Override
+	protected boolean areItemHandlersPrivate() {
+		return false;
+	}
+
+	@Override
+	protected boolean areItemHandlersPrivate() {
+		return false;
```
Comment (TheBusyBiscuit) [inline src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/PickaxeOfContainment.java]: You added this method twice

File: src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/HunterTalisman.java [hunk 2]
```diff
@@ -17,7 +17,12 @@
 	public HunterTalisman(SlimefunItemStack item, ItemStack[] recipe, boolean consumable, boolean cancelEvent, String messageSuffix, int chance) {
 		super(item, recipe, consumable, cancelEvent, messageSuffix, chance);
 	}
-	
+
+	@Override
+	protected boolean areItemHandlersPrivate() {
+		return false;
```
Comment (TheBusyBiscuit) [inline src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/items/HunterTalisman.java]: This class does not need this method, it doesn't inherit from SimpleSlimefunItem.

File: src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/gps/GPSTransmitter.java [hunk 3]
```diff
@@ -38,7 +38,12 @@ public boolean onBreak(Player p, Block b, SlimefunItem item, UnregisterReason re
 			}
 		});
 	}
-	
+
+	@Override
+	protected boolean areItemHandlersPrivate() {
+		return false;
```
Comment (TheBusyBiscuit) [inline src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/machines/electric/gps/GPSTransmitter.java]: This class does not need this method.
