### PR TITLE
Fix Disabled items still working in disabled worlds.

### LINKED ISSUE #735: Disabling item per world not working.
## Description (Required)
I'm trying to disable some items in some world. For example I don't want players to use Lumber Axe on my Main Map because we have there a region with free wood and Lumber Axe allows to destroy whole region in few clicks. I tried to block it in whitelist.yml and items.yml but with no effect. When player right click with Axe there is a warning "This item is disabled in this world" but it's still usable by left click.

## Evidence / Proof (Required)
1. Disable item in choosen world.
2. Go to this world. Try right click with this item and try left click.

## Environment (Required)
[Server thread/INFO]: This server is running CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

[01:18:36] [Server thread/INFO]: CraftBukkit v1_12_R1
[01:18:36] [Server thread/INFO]:
[01:18:36] [Server thread/INFO]: CS-CoreLib vv1.5.18
[01:18:36] [Server thread/INFO]: Slimefun vv4.1.15
[01:18:36] [Server thread/INFO]:
[01:18:36] [Server thread/INFO]: Installed Addons (1)
[01:18:36] [Server thread/INFO]: ExoticGarden v1.6.3

### PR DESCRIPTION
**Pull request by dniym**
Fixes #735

### CODE REVIEW

File: src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java [hunk 1]
```diff
@@ -98,9 +98,34 @@ else if (SlimefunManager.isItemSimiliar(slot1, SlimefunGuide.getItem(BookDesign.
 		}
 	}
 
+	/*
+	 * Handles Left click use and checks for disabled items.
+	 */
+	@EventHandler
+	public void enabledCheck(PlayerInteractEvent e) {
+		if(e.getAction() == Action.RIGHT_CLICK_AIR || e.getAction() == Action.RIGHT_CLICK_BLOCK)
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java]: Don't forget Action.PHYSICAL for Pressure Plates, we don't need that triggered.
You should instead check for LEFT_CLICK Actions instead (Just in case more Actions get added)

**Comment by TheBusyBiscuit** [comment]
Oh sure... What I wanted to test didn't work earlier but works on this one, sure...
