### PR TITLE
Fix #1104

### LINKED ISSUE #1104: Boot of the Stomper can "kill" the totem of undying
## Description (Required)
If the area don't have the flag "tnt deny" the boots hurts the player or can kill him. If the player have the Totem, the boots take off that item and the player is save.
## Steps to reproduce the Issue (Required)
[Test video](https://imgur.com/6Flk88F)
- 2 Players
- 1 with the boots / other with the totem
- The player with the boots must fall from a moderate height
-- The player with the totem take damage. If the damage is to much, the player dies and the totem is used. If the damage is moderate, the player only loses a few hearts. --

## Expected behavior (Required)
The boots can't hurt or kill players in protected areas.
As the "Test video" show, the players are in a protected area (spawn) withe this [flags](https://imgur.com/3U9ctCs)
If I put the flag "tnt deny", players are save. This should not happen, since it is a protected area and the boots shouldn't hurt

## Server Log / Error Report
Clean, no errors. Just an inssue.

## Environment (Required)
[Versions info](https://imgur.com/ifbV7r5)

### PR DESCRIPTION
**Pull request by WalshyDev**
## Description
Fixes #1104, also improves performance and formatting

## Changes
Added PVP check from ProtectionModule and small changes to improve performance.

## Related Issues
Resolves #1104 

## Testability

- [X] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.

### CODE REVIEW

File: src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java [hunk 1]
```diff
@@ -32,48 +34,73 @@ public ArmorListener(SlimefunPlugin plugin) {
...
+	@EventHandler(priority = EventPriority.MONITOR)
 	public void onDamage(EntityDamageEvent e) {
 		if (e.getEntity() instanceof Player && !e.isCancelled()) {
 			Player p = (Player) e.getEntity();
 			for (ItemStack armor: p.getInventory().getArmorContents()) {
-				if (armor != null && SlimefunItem.getByItem(armor) != null) {
-					if (SlimefunItem.getByItem(armor).isItem(SlimefunItems.ENDER_BOOTS) && Slimefun.hasUnlocked(p, SlimefunItems.ENDER_BOOTS, true)) {
-						if (e instanceof EntityDamageByEntityEvent && ((EntityDamageByEntityEvent) e).getDamager() instanceof EnderPearl) e.setCancelled(true);
+				SlimefunItem item = SlimefunItem.getByItem(armor);
+				if (armor != null && item != null) {
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: Slimefunitem.getByItem() returns null if the given item is also null,
so this "armor != null" check is redundant.

File: src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java [hunk 2]
```diff
@@ -32,48 +34,73 @@ public ArmorListener(SlimefunPlugin plugin) {
...
+					if (item.isItem(SlimefunItems.ENDER_BOOTS)
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: Comparing the ItemStacks seems a bit harsh, you should just compare the id instead, much lighter.

File: src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java [hunk 3]
```diff
@@ -32,48 +34,73 @@ public ArmorListener(SlimefunPlugin plugin) {
...
+						&& Slimefun.hasUnlocked(p, SlimefunItems.ENDER_BOOTS, true)
+						&& e instanceof EntityDamageByEntityEvent
+						&& ((EntityDamageByEntityEvent) e).getDamager() instanceof EnderPearl
+					) {
+						e.setCancelled(true);
 					}
-					else if (SlimefunItem.getByItem(armor).isItem(SlimefunItems.SLIME_BOOTS) && Slimefun.hasUnlocked(p, SlimefunItems.SLIME_BOOTS, true)) {
-						if (e.getCause() == DamageCause.FALL) e.setCancelled(true);
+					else if (item.isItem(SlimefunItems.SLIME_BOOTS)
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: Comparing the ItemStacks seems a bit harsh, you should just compare the id instead, much lighter.

File: src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java [hunk 4]
```diff
@@ -32,48 +34,73 @@ public ArmorListener(SlimefunPlugin plugin) {
...
+						p.setVelocity(new Vector(0.0, 0.7, 0.0));
+						for (Entity n: p.getNearbyEntities(4, 4, 4)) {
+							if (n instanceof LivingEntity && !n.getUniqueId().equals(p.getUniqueId())) {
+								n.setVelocity(n.getLocation().toVector().subtract(p.getLocation().toVector())
+									.normalize().multiply(1.4));
+								if (p.getWorld().getPVP()
+									&& SlimefunPlugin.getProtectionManager()
+									.hasPermission(p, n.getLocation(), ProtectionModule.Action.PVP)
+								) {
+									EntityDamageByEntityEvent event = new EntityDamageByEntityEvent(p, n,
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: I am curious why some protection plugins don't seem to listen to the event being called, that alone should theoretically suffice...

File: src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java [hunk 5]
```diff
@@ -32,48 +34,73 @@ public ArmorListener(SlimefunPlugin plugin) {
...
 							}
 						}
+
+						for (BlockFace face: BlockFace.values()) {
+							Block b = p.getLocation().getBlock().getRelative(BlockFace.DOWN).getRelative(face);
+							p.getWorld().playEffect(b.getLocation(), Effect.STEP_SOUND, b.getType());
+						}
 					}
-					else if (SlimefunItem.getByItem(armor).isItem(SlimefunItems.SLIME_BOOTS_STEEL) && Slimefun.hasUnlocked(p, SlimefunItems.SLIME_BOOTS_STEEL, true) && e.getCause() == DamageCause.FALL) e.setCancelled(true);
+					else if (item.isItem(SlimefunItems.SLIME_BOOTS_STEEL)
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: Comparing the ItemStacks seems a bit harsh, you should just compare the id instead, much lighter.

File: src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java [hunk 6]
```diff
@@ -32,48 +34,73 @@ public ArmorListener(SlimefunPlugin plugin) {
...
 	}
 	
 	@EventHandler
 	public void onTrample(PlayerInteractEvent e) {
-		if (e.getAction() == Action.PHYSICAL && e.getClickedBlock().getType() == Material.FARMLAND && SlimefunManager.isItemSimiliar(e.getPlayer().getInventory().getBoots(), SlimefunItem.getItem("FARMER_SHOES"), true)) e.setCancelled(true);
+		if (e.getAction() == Action.PHYSICAL
+			&& e.getClickedBlock() != null
+			&& e.getClickedBlock().getType() == Material.FARMLAND
+			&& SlimefunManager.isItemSimiliar(e.getPlayer().getInventory().getBoots(),
+			SlimefunItem.getItem("FARMER_SHOES"), true)
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: You should use SlimefunItems.FARMER_SHOES instead, SlimefunItem.getItem() is a heavy call that involves a loop.

File: src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java (hunk 4 above)
Comment (WalshyDev) [reply src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: Yeah I was thinking this last night, things are... weird to say the least.

File: src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java (hunk 2 above)
Comment (WalshyDev) [reply src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: Is there a good way of getting the ID for things like Ender Boots here? Looking around it seems the IDs are hardcoded in SlimefunSetup and aren't easily derived from anywhere.

Comment (TheBusyBiscuit) [reply src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: Sadly not, maybe we could have a utility class for that...
Too much work though.

For now it's fine to hard-code it in. After all they haven't changed since years and probably never will but I know it's a bad design.

File: src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java [hunk 7]
```diff
@@ -32,48 +34,73 @@ public ArmorListener(SlimefunPlugin plugin) {
...
 		if (e.getEntity() instanceof Player && !e.isCancelled()) {
 			Player p = (Player) e.getEntity();
 			for (ItemStack armor: p.getInventory().getArmorContents()) {
-				if (armor != null && SlimefunItem.getByItem(armor) != null) {
-					if (SlimefunItem.getByItem(armor).isItem(SlimefunItems.ENDER_BOOTS) && Slimefun.hasUnlocked(p, SlimefunItems.ENDER_BOOTS, true)) {
-						if (e instanceof EntityDamageByEntityEvent && ((EntityDamageByEntityEvent) e).getDamager() instanceof EnderPearl) e.setCancelled(true);
+				SlimefunItem item = SlimefunItem.getByItem(armor);
+				if (item != null) {
+					if (item.getID().equals("ENDER_BOOTS")
+						&& Slimefun.hasUnlocked(p, SlimefunItems.ENDER_BOOTS, true)
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/Slimefun/listeners/ArmorListener.java]: Sorry, that I didn't point this out earlier.

Slimefun.hasUnlocked() makes a call to Slimefunitem.getByItem() that is not neccessary here.
Instead you can just use Slimefun.hasUnlocked(Player, SlimefunItem, boolean) instead and directly pass the item variable.

That'd increase performance a lot as well.
This also applies to all the other occasions down below.
